blank_issues_enabled: false
contact_links:
  - name: GraphHopper Forum
    url: https://discuss.graphhopper.com/
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://www.graphhopper.com/contact-form/
    about: Please report security vulnerabilities here.