name: trigger_measurement

on: push

jobs:
  trigger_measurement:
    runs-on: ubuntu-22.04
    environment: benchmarks
    steps:
      - name: trigger
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.MEASUREMENT_TOKEN }}" \
          -H "Accept: application/vnd.github+json" \
          "https://api.github.com/repos/${{ secrets.MEASUREMENT_REPO }}/dispatches" \
          -d '{"event_type":"measurement_core","client_payload":{"core_commit": "${GITHUB_SHA}" }}'
